#!/usr/bin/env python3
r"""
cross_trial_type_region_variable_heatmap_out_behaviour.py
================================================================================

Variant of cross_trial_type_region_variable_heatmap.py (heatmap_PCA_PCCA.py),
adapted per three explicit changes:

  1. Columns restricted to two external variables: reward_presence and
     reward_consumption (position / speed dropped).
  2. Row 0 remains PCA(hub); all subsequent rows now come from the
     pCCA_out_behaviour analysis (behavioural-nuisance-removed pCCA) rather
     than plain pCCA, sourced from
         Paper_output/cross_trial_type_pCCA_out_behaviour_{REFERENCE_TYPE}_peak_delta_variance/
             behavior_variance_records.csv
     One row per partner region, same anatomical-order convention as before.
  3. Layout: because each hub's matrix is now only 2 columns wide, hubs no
     longer get one figure each. Instead every hub becomes one subplot
     (its own small heatmap panel), and all hub subplots are placed side by
     side in a single row of ONE combined figure (one figure per entry of
     COMPONENTS_TO_PLOT, in the usual case just one figure total).

Everything else -- CSV schema, pair-canonicalisation, anatomical ordering,
display-name overrides, "primitive copying not importing" convention -- is
unchanged from the parent script.

The colour-scale range is now an explicit, exposed hyperparameter:
HEATMAP_VMIN / HEATMAP_VMAX, default [0.0, 0.05].

Author: Oxford Neural Analysis Pipeline
Date:   2026
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# =============================================================================
# 1.  GLOBAL CONFIG
# =============================================================================

# ---- paths ------------------------------------------------------------
BASE_DIR = Path("/Users/shengyuancai/Downloads/Oxford_dataset")
PAPER_OUTPUT_DIR = BASE_DIR / "Paper_output"

REFERENCE_TYPE = "cued_hit_long"        # folder-name suffix; matches REFERENCE_TYPE
                                         # in the parent (pca / pcca_out_behaviour) scripts

# CHANGE (2): "pcca" replaced by "pcca_out_behaviour", pointed at the
# pCCA_out_behaviour output folder. Note the folder name preserves the
# literal "pCCA_out_behaviour" casing as generated by that parent script --
# it does NOT follow the all-lowercase pattern used by the pca/cca folders.
CSV_PATHS: Dict[str, Path] = {
    "pca": PAPER_OUTPUT_DIR / f"cross_trial_type_pca_{REFERENCE_TYPE}_peak_delta_variance"
                             / "behavior_variance_records.csv",
    "pcca_out_behaviour": PAPER_OUTPUT_DIR / f"cross_trial_type_pCCA_out_behaviour_{REFERENCE_TYPE}_peak_delta_variance"
                                            / "behavior_variance_records.csv",
}

TRIAL_TYPE_TO_PLOT = "cued_hit_long"    # 'cued_hit_long'   -> task 3 (reference condition)
                                         # 'spont_hit_long'  -> task 4 (projected)
                                         # 'spont_miss_long' -> task 4 (projected)

# ---- regions --------------------------------------------------------------
REGIONS_OF_INTEREST: List[str] = ["ORB", "MOp", "MOs", "STR", "VALVM", "VPMPO", "HY"]

ANATOMICAL_ORDER: List[str] = [
    "mPFC", "ORB", "MOp", "MOs", "OLF",
    "STR", "STRv",
    "MD", "LP", "VALVM", "VPMPO", "ILM",
    "HY",
]

# ---- external variables (columns) ------------------------------------------
# CHANGE (1): position / speed dropped; only the two reward-related
# predictors remain.
EXTERNAL_VARIABLES: List[Tuple[str, str]] = [
    ("reward_presence", "Reward presence"),
    ("reward_consumption", "Reward consumption"),
]

# ---- components -------------------------------------------------------
COMPONENTS_TO_PLOT: List[int] = [0]     # e.g. [0, 1, 2] -> one combined figure PER component

# ---- display names ----------------------------------------------------
DISPLAY_NAME_OVERRIDES: Dict[str, str] = {
    "VALVM": "motor Thal",
    "VPMPO": "sens Thal",
    "ORB": "OFC",
    "MOp": "M1 Ctx",
    "MOs": "preM Ctx",
}

# ---- heatmap appearance -------------------------------------------------
HEATMAP_CMAP = "Reds"
# CHANGE: colour range is now an explicit hyperparameter pair, default [0, 0.05].
HEATMAP_VMIN: float = 0.0
HEATMAP_VMAX: Optional[float] = 0.2    # None -> shared max across every plotted cell
ANNOTATE_CELLS = False                  # True to print R^2 values inside cells
MISSING_CELL_COLOR = "#d9d9d9"          # a missing record renders distinctly from R^2 = 0

# ---- typography ---------------------------------------------------------
TITLE_FONTSIZE = 15
TICK_FONTSIZE = 15
LABEL_FONTSIZE = 15

# ---- output -----------------------------------------------------------
FIGURE_OUTPUT_DIR = PAPER_OUTPUT_DIR / "figures_region_PCA_PCCA_out_behaviour_variable_heatmap"
SAVE_FORMATS: Tuple[str, ...] = ("png",)
SAVE_DPI = 400
SHOW_FIGURES = False
PRINT_SUMMARY_TABLES = True


# =============================================================================
# 2.  SMALL PRIMITIVES (copied, not imported)
# =============================================================================

def get_anatomical_index(region: str) -> int:
    try:
        return ANATOMICAL_ORDER.index(region)
    except ValueError:
        print(f"[warn] '{region}' not found in the local ANATOMICAL_ORDER copy; "
              f"sorting it last. Add it to ANATOMICAL_ORDER above if that's unexpected.")
        return len(ANATOMICAL_ORDER)


def anatomical_sort(regions: Sequence[str]) -> List[str]:
    return sorted(regions, key=get_anatomical_index)


def _display_name(region: str) -> str:
    return DISPLAY_NAME_OVERRIDES.get(region, region)


def sort_pair_by_anatomy(region_i: str, region_j: str) -> Tuple[str, str]:
    """Anatomical canonicalisation (copied per project convention): the
    anatomically-earlier region is always region_i."""
    a, b = sorted((region_i, region_j), key=get_anatomical_index)
    return a, b


# =============================================================================
# 3.  ROW SPECIFICATION
# =============================================================================

@dataclass(frozen=True)
class RowSpec:
    analysis: str                   # "pca" or "pcca_out_behaviour"
    hub: str                        # raw region code (this panel's region)
    partner: Optional[str] = None   # raw region code; None for the PCA row

    @property
    def label(self) -> str:
        if self.analysis == "pca":
            return "PCA"
        return f"with {_display_name(self.partner)}"


def build_row_specs(hub: str) -> List[RowSpec]:
    """Row 0 = PCA(hub); rows 1..N = pCCA_out_behaviour(hub, partner) for
    every other region in REGIONS_OF_INTEREST, anatomically ordered."""
    specs: List[RowSpec] = [RowSpec(analysis="pca", hub=hub)]
    partners = anatomical_sort([r for r in REGIONS_OF_INTEREST if r != hub])
    specs += [RowSpec(analysis="pcca_out_behaviour", hub=hub, partner=p) for p in partners]
    return specs


# =============================================================================
# 4.  DATA LOADING
# =============================================================================

REQUIRED_COMMON_COLUMNS = {"session", "component", "predictor", "r2", "trial_type"}


def _load_csv(analysis: str) -> pd.DataFrame:
    path = CSV_PATHS[analysis]
    if not path.exists():
        raise FileNotFoundError(
            f"Could not find the {analysis.upper()} behavior-variance CSV at:\n    {path}\n"
            f"Check BASE_DIR / CSV_PATHS at the top of the script."
        )
    df = pd.read_csv(path)
    missing = REQUIRED_COMMON_COLUMNS - set(df.columns)
    if missing:
        raise ValueError(f"{path.name} ({analysis}) is missing expected column(s): "
                          f"{sorted(missing)}. Columns found: {sorted(df.columns)}")
    has_pair_cols = {"region_i", "region_j"}.issubset(df.columns)
    has_single_col = "region" in df.columns
    if not (has_pair_cols or has_single_col):
        raise ValueError(f"{path.name} ({analysis}) has neither 'region' nor "
                          f"'region_i'/'region_j' -- can't tell which region(s) each row is for.")
    return df


def load_all_tables() -> Dict[str, pd.DataFrame]:
    tables: Dict[str, pd.DataFrame] = {}
    for analysis in ("pca", "pcca_out_behaviour"):
        tables[analysis] = _load_csv(analysis)
    return tables


def _validate_tables(tables: Dict[str, pd.DataFrame]) -> None:
    wanted_predictors = {key for key, _label in EXTERNAL_VARIABLES}
    for analysis, df in tables.items():
        found_predictors = set(df["predictor"].unique())
        missing_predictors = wanted_predictors - found_predictors
        if missing_predictors:
            print(f"[warn] {analysis.upper()}: predictor(s) {sorted(missing_predictors)} "
                  f"not present; available: {sorted(found_predictors)}")

        found_trial_types = set(df["trial_type"].unique())
        if TRIAL_TYPE_TO_PLOT not in found_trial_types:
            print(f"[warn] {analysis.upper()}: TRIAL_TYPE_TO_PLOT='{TRIAL_TYPE_TO_PLOT}' "
                  f"not present; available: {sorted(found_trial_types)}")

        if "region" in df.columns:
            found_regions = set(df["region"].unique())
        else:
            found_regions = set(df["region_i"].unique()) | set(df["region_j"].unique())
        missing_regions = set(REGIONS_OF_INTEREST) - found_regions
        if missing_regions:
            print(f"[warn] {analysis.upper()}: region(s) {sorted(missing_regions)} from "
                  f"REGIONS_OF_INTEREST not present in this table.")


# =============================================================================
# 5.  R^2 LOOKUP
# =============================================================================

def _pca_row_mask(df: pd.DataFrame, hub: str) -> pd.Series:
    if "region" in df.columns:
        return df["region"] == hub
    region_j_empty = df["region_j"].isna() if "region_j" in df.columns else True
    return (df["region_i"] == hub) & region_j_empty


def _pair_row_mask(df: pd.DataFrame, hub: str, partner: str) -> pd.Series:
    """Mask for any pairwise (pCCA-family) analysis table -- used here for
    pcca_out_behaviour, same schema convention as plain pCCA had."""
    region_i, region_j = sort_pair_by_anatomy(hub, partner)
    mask = (df["pair"] == f"('{region_i}', '{region_j}')") & (df["region"] == hub)
    return mask


def lookup_r2(spec: RowSpec, predictor: str, component: int, tables: Dict[str, pd.DataFrame]) -> float:
    df = tables.get(spec.analysis)
    if df is None:
        return np.nan

    mask = ((df["predictor"] == predictor)
            & (df["component"] == component)
            & (df["trial_type"] == TRIAL_TYPE_TO_PLOT))
    if spec.analysis == "pca":
        mask &= _pca_row_mask(df, spec.hub)
    else:
        mask &= _pair_row_mask(df, spec.hub, spec.partner)

    values = df.loc[mask, "r2"]
    if values.empty:
        partner_txt = "" if spec.partner is None else f" \u00d7 {_display_name(spec.partner)}"
        print(f"[warn] no rows for {spec.analysis.upper()} {_display_name(spec.hub)}{partner_txt}, "
              f"predictor='{predictor}', component={component}, trial_type='{TRIAL_TYPE_TO_PLOT}'.")
        return np.nan
    return float(values.mean())     # mean R^2 across sessions


# =============================================================================
# 6.  MATRIX CONSTRUCTION
# =============================================================================

def build_matrix(hub: str, component: int, tables: Dict[str, pd.DataFrame]) -> Tuple[List[RowSpec], np.ndarray]:
    row_specs = build_row_specs(hub)
    matrix = np.full((len(row_specs), len(EXTERNAL_VARIABLES)), np.nan)
    for i, spec in enumerate(row_specs):
        for j, (predictor_key, _label) in enumerate(EXTERNAL_VARIABLES):
            matrix[i, j] = lookup_r2(spec, predictor_key, component, tables)
    return row_specs, matrix


# =============================================================================
# 7.  PLOTTING
# =============================================================================

def _draw_heatmap(ax, matrix: np.ndarray, row_labels: List[str],
                   vmin: float, vmax: float, show_row_labels: bool):
    masked = np.ma.masked_invalid(matrix)
    cmap = plt.get_cmap(HEATMAP_CMAP).copy()
    cmap.set_bad(color=MISSING_CELL_COLOR)

    im = ax.imshow(masked, cmap=cmap, vmin=vmin, vmax=vmax, aspect="auto")

    ax.set_xticks(range(len(EXTERNAL_VARIABLES)))
    ax.set_xticklabels([label for _key, label in EXTERNAL_VARIABLES],
                        fontsize=TICK_FONTSIZE, rotation=40, ha="right", rotation_mode="anchor")

    ax.set_yticks(range(len(row_labels)))
    ax.set_yticklabels(row_labels if show_row_labels else [""] * len(row_labels), fontsize=TICK_FONTSIZE)

    ax.set_xticks(np.arange(-0.5, len(EXTERNAL_VARIABLES), 1), minor=True)
    ax.set_yticks(np.arange(-0.5, len(row_labels), 1), minor=True)
    ax.grid(which="minor", color="white", linewidth=1.5)
    ax.tick_params(which="both", length=0)

    if ANNOTATE_CELLS:
        for i in range(matrix.shape[0]):
            for j in range(matrix.shape[1]):
                if not np.isnan(matrix[i, j]):
                    ax.text(j, i, f"{matrix[i, j]:.2f}", ha="center", va="center",
                             fontsize=max(TICK_FONTSIZE - 6, 8))

    return im


def plot_all_hubs_figure(
    hubs: List[str],
    component: int,
    cache: Dict[Tuple[str, int], Tuple[List[RowSpec], np.ndarray]],
    vmin: float,
    vmax: float,
) -> plt.Figure:
    """CHANGE (3): one combined figure, one subplot PER hub, hubs placed
    side by side in anatomical order (as passed in via `hubs`)."""
    n_hubs = len(hubs)
    fig_width = 3 * n_hubs + 2.0
    fig, axes = plt.subplots(1, n_hubs, figsize=(fig_width, 4.6), squeeze=False,
                              constrained_layout=True)
    axes = axes[0]

    im = None
    for idx, (ax, hub) in enumerate(zip(axes, hubs)):
        row_specs, matrix = cache[(hub, component)]
        row_labels = [s.label for s in row_specs]
        im = _draw_heatmap(ax, matrix, row_labels, vmin, vmax, show_row_labels=(idx != 10))
        ax.set_title(_display_name(hub), fontsize=TITLE_FONTSIZE - 2)

    if len(COMPONENTS_TO_PLOT) > 1:
        fig.suptitle(f"Component {component + 1}", fontsize=TITLE_FONTSIZE, fontweight="normal")

    cbar = fig.colorbar(im, ax=axes.tolist(), fraction=0.05, pad=0.02)
    cbar.set_ticks([vmin, (vmin + vmax) / 2, vmax])
    cbar.set_label("Mean $R^2$ of GLM", fontsize=LABEL_FONTSIZE)
    cbar.ax.tick_params(labelsize=max(TICK_FONTSIZE - 4, 8))

    return fig


def _print_summary(hub: str, cache: Dict[Tuple[str, int], Tuple[List[RowSpec], np.ndarray]]) -> None:
    for component in COMPONENTS_TO_PLOT:
        row_specs, matrix = cache[(hub, component)]
        print(f"\n--- {_display_name(hub)} | component {component} ---")
        header = "".join(f"{label:>20s}" for _key, label in EXTERNAL_VARIABLES)
        print(f"{'':<20s}{header}")
        for spec, row in zip(row_specs, matrix):
            row_txt = "".join(f"{v:20.3f}" if not np.isnan(v) else f"{'--':>20s}" for v in row)
            print(f"{spec.label:<20s}{row_txt}")


# =============================================================================
# 8.  MAIN
# =============================================================================

def main() -> None:
    print("=" * 70)
    print("REGION (subplot) x pCCA_out_behaviour-PARTNER  vs  REWARD-VARIABLE  HEATMAPS")
    print("=" * 70)
    print(f"  regions of interest : {REGIONS_OF_INTEREST}")
    print(f"  components to plot  : {COMPONENTS_TO_PLOT}")
    print(f"  trial type          : {TRIAL_TYPE_TO_PLOT}")
    print(f"  external variables  : {[k for k, _ in EXTERNAL_VARIABLES]}")
    print(f"  colour range        : [{HEATMAP_VMIN}, {HEATMAP_VMAX}]")
    print(f"  output directory    : {FIGURE_OUTPUT_DIR}")
    print("=" * 70)

    tables = load_all_tables()
    _validate_tables(tables)

    hubs = anatomical_sort(REGIONS_OF_INTEREST)

    cache: Dict[Tuple[str, int], Tuple[List[RowSpec], np.ndarray]] = {
        (hub, component): build_matrix(hub, component, tables)
        for hub in hubs
        for component in COMPONENTS_TO_PLOT
    }

    vmin = HEATMAP_VMIN
    if HEATMAP_VMAX is not None:
        vmax = HEATMAP_VMAX
    else:
        stacked = np.concatenate([m.ravel() for _specs, m in cache.values()])
        vmax = 1.0 if np.all(np.isnan(stacked)) else float(np.nanmax(stacked))
    print(f"\n[info] colour-scale range in use (mean R^2): [{vmin}, {vmax}]")

    FIGURE_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    if PRINT_SUMMARY_TABLES:
        for hub in hubs:
            _print_summary(hub, cache)

    for component in COMPONENTS_TO_PLOT:
        fig = plot_all_hubs_figure(hubs, component, cache, vmin, vmax)
        stem = (f"region_variable_heatmap_out_behaviour_component{component}"
                if len(COMPONENTS_TO_PLOT) > 1 else "region_variable_heatmap_out_behaviour")
        for fmt in SAVE_FORMATS:
            out_path = FIGURE_OUTPUT_DIR / f"{stem}.{fmt}"
            fig.savefig(out_path, dpi=SAVE_DPI, bbox_inches="tight")
            print(f"[info] saved {out_path}")
        if SHOW_FIGURES:
            plt.show()
        plt.close(fig)

    print("\n" + "=" * 70)
    print("DONE")
    print("=" * 70)


if __name__ == "__main__":
    main()