"""
DSA Pedagogical Example — using the official dsa-metric package.
pip install dsa-metric

Two neural populations (N=10 neurons each):
  Pop A   : ring attractor  (limit cycle, S¹ topology)
  Pop B_c : ring attractor, different random readout W  (conjugate to A)
  Pop B_d : stable fixed point  (different topology from A)
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

# ─── official package imports ────────────────────────────────────────────────
from DSA import DSA
from DSA.dmd import DMD
from DSA.simdist import SimilarityTransformDist


# ══════════════════════════════════════════════════════════════════════════════
# §1  SIMULATE NEURAL POPULATIONS
#
# Each population is generated by projecting a low-dimensional latent
# trajectory through a random readout matrix W ∈ ℝ^{2 × N}.
#
#   r(t) = W x(t) + ε,    ε ~ N(0, σ²)
#
# Two populations with DIFFERENT W but the SAME latent x(t) are
# *conjugate*: same dynamics, different geometry.
# ══════════════════════════════════════════════════════════════════════════════

def simulate_ring(N: int = 10, T: int = 600, noise: float = 0.04, seed: int = 0):
    """
    Limit-cycle (ring) attractor.
    Latent:  x(t) = [sin(t),  cos(t)]   → closed orbit on S¹.
    Shape returned: (T, N)
    """
    rng = np.random.default_rng(seed)
    t   = np.linspace(0, 6 * np.pi, T)          # ~3 full cycles
    lat = np.column_stack([np.sin(t), np.cos(t)])  # (T, 2)
    W   = rng.standard_normal((2, N))
    return lat @ W + noise * rng.standard_normal((T, N))


def simulate_fixed_point(N: int = 10, T: int = 600, noise: float = 0.04, seed: int = 0):
    """
    Stable fixed-point attractor.
    Latent:  x(t) = e^{-t/3} [sin(4t), cos(4t)]  → spiral converging to origin.
    Topology is fundamentally different from the ring (S¹ vs ℝ⁰).
    Shape returned: (T, N)
    """
    rng = np.random.default_rng(seed)
    t   = np.linspace(0, 12, T)
    lat = np.column_stack([np.exp(-t / 3) * np.sin(4 * t),
                            np.exp(-t / 3) * np.cos(4 * t)])
    W   = rng.standard_normal((2, N))
    return lat @ W + noise * rng.standard_normal((T, N))


np.random.seed(42)
N_NEURONS = 10
T         = 600

pop_A  = simulate_ring(N_NEURONS, T, seed=1)   # (T, N)
pop_Bc = simulate_ring(N_NEURONS, T, seed=3)   # conjugate ring
pop_Bd = simulate_fixed_point(N_NEURONS, T, seed=3)

#%%
# ══════════════════════════════════════════════════════════════════════════════
# §2  VISUALISE NEURAL VECTOR FIELDS IN LATENT SPACE
#
# The DSA package works on data of shape (trials, time, channels) or
# (time, channels).  We add a singleton trial dimension: (1, T, N).
#
# To inspect the *neural vector field* we:
#   (a) Reduce to 2-D via PCA for visualisation.
#   (b) At each sampled latent state z_t, plot the flow  Δz = z_{t+1} - z_t
#       as an arrow.  This is the empirical vector field in latent space.
# ══════════════════════════════════════════════════════════════════════════════

from sklearn.decomposition import PCA

def get_pca_trajectory(X: np.ndarray, n_components: int = 2):
    """Project (T, N) activity into top principal components."""
    pca = PCA(n_components=n_components)
    return pca.fit_transform(X), pca          # (T, 2)


def plot_vector_field(ax, Z: np.ndarray, title: str, color: str,
                      subsample: int = 8):
    """
    Plot empirical vector field from latent trajectory Z ∈ ℝ^{T×2}.

    At each sampled time point t, the arrow represents:
        Δz(t) = z(t+1) − z(t)        (discrete-time flow)

    This is the observed neural vector field before any Koopman fitting.
    """
    T_ = len(Z)
    t_idx = np.arange(0, T_ - 1, subsample)

    # Background: coloured trajectory
    ax.scatter(Z[:, 0], Z[:, 1], c=np.arange(T_),
               cmap='plasma', s=4, alpha=0.6, linewidths=0)

    # Foreground: flow arrows
    dZ = np.diff(Z, axis=0)                          # (T-1, 2)
    ax.quiver(Z[t_idx, 0], Z[t_idx, 1],
              dZ[t_idx, 0], dZ[t_idx, 1],
              color=color, alpha=0.8, scale=None,
              scale_units='xy', angles='xy',
              width=0.004, headwidth=4)

    ax.set_title(title, fontsize=10, color=color, fontweight='bold')
    ax.set_xlabel(r'$\mathrm{PC}_1$', fontsize=9)
    ax.set_ylabel(r'$\mathrm{PC}_2$', fontsize=9)
    ax.set_aspect('equal')


Z_A,  _  = get_pca_trajectory(pop_A)
Z_Bc, _  = get_pca_trajectory(pop_Bc)
Z_Bd, _  = get_pca_trajectory(pop_Bd)

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
plot_vector_field(axes[0], Z_A,  'Pop A  (ring)', '#2166ac')
plot_vector_field(axes[1], Z_Bc, r'Pop $B_c$  (conjugate ring)', '#4dac26')
plot_vector_field(axes[2], Z_Bd, r'Pop $B_d$  (fixed point)', '#d01c8b')
fig.suptitle(r'Neural Vector Fields in PC Space'
             '\n'
             r'Arrows: $\Delta \mathbf{z}(t) = \mathbf{z}(t+1) - \mathbf{z}(t)$',
             fontsize=12)
plt.tight_layout()
plt.savefig('neural_vector_fields.png', dpi=150, bbox_inches='tight')



  #%%
# ══════════════════════════════════════════════════════════════════════════════
# §3  FIT KOOPMAN OPERATORS VIA THE OFFICIAL DMD CLASS
#
# DMD expects shape (trials, time, channels) or (time, channels).
# We use (T, N) directly.
#
# Key hyperparameters:
#   n_delays  p  — Hankel window length (Takens embedding depth)
#   rank      r  — truncation of Koopman approximation
#
# After fitting, the attribute  dmd.A_v  holds  K ∈ ℝ^{r×r}.
# ══════════════════════════════════════════════════════════════════════════════

N_DELAYS = 20
RANK     = 10

def fit_koopman(X: np.ndarray, n_delays: int = N_DELAYS, rank: int = RANK) -> DMD:
    """
    Fit a HAVOK–DMD model to neural activity X ∈ ℝ^{T×N}.
    Returns the fitted DMD object; K is in dmd.A_v.
    """
    dmd = DMD(X, n_delays=n_delays, rank=rank)
    dmd.fit()
    return dmd


dmd_A  = fit_koopman(pop_A)
dmd_Bc = fit_koopman(pop_Bc)
dmd_Bd = fit_koopman(pop_Bd)

Ka  = dmd_A.A_v.numpy()    # (r, r)  Koopman matrix for pop A
Kbc = dmd_Bc.A_v.numpy()   # (r, r)  Koopman matrix for pop B_c
Kbd = dmd_Bd.A_v.numpy()   # (r, r)  Koopman matrix for pop B_d


def plot_koopman_vector_field(ax, K: np.ndarray, title: str, color: str,
                              grid_n: int = 14):
    """
    Visualise the LINEAR vector field defined by  ψ̇ = K ψ
    on a 2-D grid spanned by the first two Koopman modes.

    At each grid point z = [z₁, z₂], the arrow represents K[:2,:2] z.
    This is the Koopman-linearised vector field, analogous to
    Figure 1 of Ostrow et al. (images you shared).
    """
    K2 = K[:2, :2]                          # project to 2-D sub-block
    lim = 1.5
    g   = np.linspace(-lim, lim, grid_n)
    ZZ1, ZZ2 = np.meshgrid(g, g)
    Z_grid   = np.stack([ZZ1.ravel(), ZZ2.ravel()], axis=1)  # (G², 2)
    dZ_grid  = (K2 @ Z_grid.T).T                              # (G², 2)

    speed = np.linalg.norm(dZ_grid, axis=1)
    speed = speed / (speed.max() + 1e-12)   # normalise for colour

    ax.streamplot(ZZ1, ZZ2,
                  dZ_grid[:, 0].reshape(grid_n, grid_n),
                  dZ_grid[:, 1].reshape(grid_n, grid_n),
                  color=color, linewidth=0.8, density=1.1, arrowsize=1.1)
    ax.set_xlim(-lim, lim); ax.set_ylim(-lim, lim)
    ax.set_title(title, fontsize=10, color=color, fontweight='bold')
    ax.set_xlabel(r'$\psi_1$', fontsize=9)
    ax.set_ylabel(r'$\psi_2$', fontsize=9)
    ax.set_aspect('equal')

    # Overlay eigenvalue info
    eigs = np.linalg.eigvals(K)
    n_complex = np.sum(np.abs(eigs.imag) > 0.05)
    ax.text(0.03, 0.96,
            fr'Complex $\lambda$: {n_complex}/{len(eigs)}',
            transform=ax.transAxes, fontsize=8,
            va='top', color=color)


fig2, axes2 = plt.subplots(1, 3, figsize=(15, 4))
plot_koopman_vector_field(axes2[0], Ka,  'Koopman field  Pop A',   '#2166ac')
plot_koopman_vector_field(axes2[1], Kbc, r'Koopman field  Pop $B_c$', '#4dac26')
plot_koopman_vector_field(axes2[2], Kbd, r'Koopman field  Pop $B_d$', '#d01c8b')
fig2.suptitle(r'Koopman-Linearised Vector Fields  '
              r'($\dot{\boldsymbol{\psi}} = \mathbf{K}\boldsymbol{\psi}$, '
              r'projected to 2-D Koopman subspace)',
              fontsize=12)
plt.tight_layout()
plt.savefig('koopman_vector_fields.png', dpi=150, bbox_inches='tight')


# ══════════════════════════════════════════════════════════════════════════════
# §4  COMPUTE DSA DISTANCES
#
# Route 1 — SimilarityTransformDist directly on the K matrices.
#            Most transparent; you supply K_a and K_b yourself.
#
# Route 2 — DSA high-level class on raw data.
#            Automates delay embedding + DMD + Procrustes in one call.
#
# Route 3 — DSA pairwise on a list of datasets.
#            Returns a full dissimilarity matrix.
#
# The paper's metric (Eq. 5):
#     d(K_a, K_b) = min_{C ∈ O(r)} ‖K_a − C K_b C^{-1}‖_F
# ══════════════════════════════════════════════════════════════════════════════

# ── Route 1: SimilarityTransformDist on pre-fitted K matrices ─────────────

simdist = SimilarityTransformDist(
    iters=2000,
    lr=5e-3,
    score_method='angular',   # angular Procrustes ∈ [0, π]
    device='cpu',
)

d_Abc  = simdist.fit_score(Ka, Kbc)   # conjugate rings  → expect LOW
d_Abd  = simdist.fit_score(Ka, Kbd)   # ring vs FP       → expect HIGH

print(f"d_DSA(A, B_c) = {d_Abc:.4f}   [conjugate, expect LOW]")
print(f"d_DSA(A, B_d) = {d_Abd:.4f}   [different topology, expect HIGH]")


# ── Route 2: High-level DSA on raw neural data ────────────────────────────
#
# DSA expects shape (trials, time, channels) or (time, channels).
# We add a singleton trial dim to be safe: (1, T, N).

pop_A_3d  = pop_A[np.newaxis]    # (1, T, N)
pop_Bc_3d = pop_Bc[np.newaxis]
pop_Bd_3d = pop_Bd[np.newaxis]

dsa_conj = DSA(
    pop_A_3d, pop_Bc_3d,
    n_delays=N_DELAYS, rank=RANK,
    score_method='angular',
    iters=2000, lr=5e-3,
)
d_conj_high = dsa_conj.fit_score()   # float

dsa_diff = DSA(
    pop_A_3d, pop_Bd_3d,
    n_delays=N_DELAYS, rank=RANK,
    score_method='angular',
    iters=2000, lr=5e-3,
)
d_diff_high = dsa_diff.fit_score()   # float

print(f"\nHigh-level DSA:")
print(f"  d(A, B_c) = {d_conj_high:.4f}")
print(f"  d(A, B_d) = {d_diff_high:.4f}")


# ── Route 3: Pairwise dissimilarity matrix ────────────────────────────────
#
# Pass a list of datasets; DSA returns an (n × n) dissimilarity matrix.

dsa_pairwise = DSA(
    [pop_A_3d, pop_Bc_3d, pop_Bd_3d],
    n_delays=N_DELAYS, rank=RANK,
    score_method='angular',
    iters=2000, lr=5e-3,
)
D = dsa_pairwise.fit_score()   # (3, 3) symmetric matrix

print(f"\nPairwise DSA dissimilarity matrix D:")
labels = ['A (ring)', 'B_c (conj.)', 'B_d (FP)']
print(f"{'':>12}", "  ".join(f"{l:>12}" for l in labels))
for i, row_label in enumerate(labels):
    print(f"{row_label:>12}", "  ".join(f"{D[i, j]:>12.4f}" for j in range(3)))


# ══════════════════════════════════════════════════════════════════════════════
# §5  EIGENSPECTRUM ANALYSIS
#
# Theorem (Budiŝić et al. 2012): If two systems are conjugate, their
# Koopman eigenspectra are identical.
#
# Therefore:
#   • Pop A and Pop B_c should have matching spectra  (same S¹ limit cycle).
#   • Pop B_d should have a qualitatively different spectrum
#     (real eigenvalues with |λ| < 1, indicating exponential decay).
# ══════════════════════════════════════════════════════════════════════════════

fig3, ax = plt.subplots(figsize=(6, 6))

theta = np.linspace(0, 2 * np.pi, 300)
ax.plot(np.cos(theta), np.sin(theta), 'k--', lw=0.8, alpha=0.3,
        label='Unit circle')

for K, label, color, marker in [
        (Ka,  'Pop A  (ring)',         '#2166ac', 'o'),
        (Kbc, r'Pop $B_c$ (conj.)',   '#4dac26', 's'),
        (Kbd, r'Pop $B_d$ (FP)',      '#d01c8b', '^')]:
    eigs = np.linalg.eigvals(K)
    ax.scatter(eigs.real, eigs.imag,
               color=color, marker=marker, s=100,
               edgecolors='k', linewidths=0.8,
               label=label, zorder=5)

ax.axhline(0, color='k', lw=0.4)
ax.axvline(0, color='k', lw=0.4)
ax.set_aspect('equal')
ax.set_xlim(-2, 2); ax.set_ylim(-2, 2)
ax.set_xlabel(r'$\mathrm{Re}(\lambda)$', fontsize=11)
ax.set_ylabel(r'$\mathrm{Im}(\lambda)$', fontsize=11)
ax.set_title(r'Koopman Eigenspectrum  $\{\lambda_i(\mathbf{K})\}$'
             '\n'
             r'Conjugate systems share the same spectrum',
             fontsize=11)
ax.legend(fontsize=9)
plt.tight_layout()
plt.savefig('koopman_eigenspectra.png', dpi=150, bbox_inches='tight')